version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: crud_mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - crud_network

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: crud_php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - crud_network

  nginx:
    image: nginx:latest
    container_name: crud_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html:ro
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - crud_network

volumes:
  dbdata:

networks:
  crud_network:
    driver: bridge
